### ISSUE TITLE
the app can't open pdf files 

### ISSUE THREAD

**Issue by zozo91** [PrivacyApps/document-viewer#250]
why I can't compile this code I tried many times 
all pdf files look white 
[https://drive.google.com/open?id=0B9x5c4hmdBIGNVloMkxjRWc5azA](url)

**Comment by ericwa** [comment]
The white book covers until the first time you open a book is a known limitation: https://github.com/SufficientlySecure/document-viewer/issues/123 

Does the app crash when you try to open a pdf?
Did you compile the apk yourself or get it from Google Play or f-droid?
Possible to get a crash log from logcat?

**Comment by skynetlabz** [comment]
The error from logcat is below

```
05-24 11:57:43.707 24278-24278/org.sufficientlysecure.viewer E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: org.sufficientlysecure.viewer, PID: 24278
                                                                               java.lang.RuntimeException: Unable to start activity ComponentInfo{org.sufficientlysecure.viewer/org.ebookdroid.ui.viewer.ViewerActivity}: java.lang.RuntimeException: java.lang.ExceptionInInitializerError
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2509)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2569)
                                                                                   at android.app.ActivityThread.access$900(ActivityThread.java:150)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1399)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:168)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5885)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
                                                                                Caused by: java.lang.RuntimeException: java.lang.ExceptionInInitializerError
                                                                                   at org.ebookdroid.core.models.DocumentModel.<init>(DocumentModel.java:74)
                                                                                   at org.ebookdroid.ui.viewer.ViewerActivityController.afterCreate(ViewerActivityController.java:242)
                                                                                   at org.ebookdroid.ui.viewer.ViewerActivityController.afterCreate(ViewerActivityController.java:98)
                                                                                   at org.emdev.ui.AbstractActionActivity.onCreate(AbstractActionActivity.java:108)
                                                                                   at android.app.Activity.performCreate(Activity.java:6262)
                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1125)
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2462)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2569) 
                                                                                   at android.app.ActivityThread.access$900(ActivityThread.java:150) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1399) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:168) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5885) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687) 
                                                                                Caused by: java.lang.ExceptionInInitializerError
                                                                                   at java.lang.Class.newInstance(Native Method)
                                                                                   at org.ebookdroid.core.models.DocumentModel.<init>(DocumentModel.java:71)
                                                                                   at org.ebookdroid.ui.viewer.ViewerActivityController.afterCreate(ViewerActivityController.java:242) 
                                                                                   at org.ebookdroid.ui.viewer.ViewerActivityController.afterCreate(ViewerActivityController.java:98) 
                                                                                   at org.emdev.ui.AbstractActionActivity.onCreate(AbstractActionActivity.java:108) 
                                                                                   at android.app.Activity.performCreate(Activity.java:6262) 
                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1125) 
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2462) 
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2569) 
                                                                                   at android.app.ActivityThread.access$900(ActivityThread.java:150) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1399) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:168) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5885) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687) 
                                                                                Caused by: java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.sufficientlysecure.viewer-1/base.apk", zip file "/data/app/org.sufficientlysecure.viewer-1/split_lib_dependencies_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-1/split_lib_slice_0_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-1/split_lib_slice_1_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-1/split_lib_slice_2_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-1/split_lib_slice_3_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-1/split_lib_slice_4_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-1/split_lib_slice_5_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-1/split_lib_slice_6_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-1/split_lib_slice_7_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-1/split_lib_slice_8_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/org.sufficientlysecure.viewer-1/lib/arm, /system/lib, /vendor/lib, system/vendor/lib, system/vendor/lib/egl, system/lib/hw]]] couldn't find "libebookdroid.so"
                                                                                   at org.ebookdroid.EBookDroidLibraryLoader.load(EBookDroidLibraryLoader.java:21)
                                                                                   at org.ebookdroid.droids.mupdf.codec.MuPdfContext.<clinit>(MuPdfContext.java:24)
                                                                                   at java.lang.Class.newInstance(Native Method) 
                                                                                   at org.ebookdroid.core.models.DocumentModel.<init>(DocumentModel.java:71) 
                                                                                   at org.ebookdroid.ui.viewer.ViewerActivityController.afterCreate(ViewerActivityController.java:242) 
                                                                                   at org.ebookdroid.ui.viewer.ViewerActivityController.afterCreate(ViewerActivityController.java:98) 
                                                                                   at org.emdev.ui.AbstractActionActivity.onCreate(AbstractActionActivity.java:108) 
                                                                                   at android.app.Activity.performCreate(Activity.java:6262) 
                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1125) 
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2462) 
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2569) 
                                                                                   at android.app.ActivityThread.access$900(ActivityThread.java:150) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1399) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:168) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5885) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687) 
                                                                                Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.sufficientlysecure.viewer-1/base.apk", zip file "/data/app/org.sufficientlysecure.viewer-1/split_lib_dependencies_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-1/split_lib_slice_0_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-1/split_lib_slice_1_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-1/split_lib_slice_2_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-1/split_lib_slice_3_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-1/split_lib_slice_4_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-1/split_lib_slice_5_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-1/split_lib_slice_6_apk.apk", zip file "/data/app/org.sufficientlysecure.vi

```

**Comment by rafal-adamek** [comment]
I confirm this bug. It happens when building the app from Android Studio and opening any PDF (menu and settings work OK). It doesn't happen when I download the apk from F-droid.

I wanted to contribute but I can't seem to find why does it crash on opening any pdf.

**Comment by ericwa** [comment]
@rafal-adamek did you follow [these](https://github.com/SufficientlySecure/document-viewer#build-with-gradle) instructions to build the native code, before compiling the Java code in Android Studio? Did the native code compile successfully?

**Comment by rafal-adamek** [comment]
@ericwa, I'm sorry but it indeed was some error with ndk-build. Compiling again fixed it. Sorry to bother you.

**Comment by ericwa** [comment]
Oh, great :)

**Comment by zozo91** [comment]
Actually Mr. Ericwa the app still not working 
I tried the instructions but I did not understand them will 
I have android studio and I applied the instructions of android studio but without any benefit 
now what I have to do please

**Comment by ericwa** [comment]
The two things you need to do outside android studio before you can build the app are:
1. run `init.sh`
2. run `ndk-build` inside the `document-viewer` subdirectory

What is your OS? `init.sh` is a bash script and assumes a unix-like OS (uses make, patch, git) so it won't work on Windows out of the box.

**Comment by zozo91** [comment]
Thank you Mr. Ericwa for your responding  
actually I have windows so will it work finely?  the steps you mentioned now looks clear I will try them then give a response.

**Comment by ericwa** [comment]
@zozo91 as far as I know, no one has tried to build Document Viewer on Windows so it will probably take some trial and error work.
I opened a new issue for discussing Windows support:
https://github.com/PrivacyApps/document-viewer/issues/257
