### ISSUE TITLE
Crash on Emulator Nexus 5X API 26

### ISSUE THREAD

**Issue by chihung93** [PrivacyApps/document-viewer#262]
```

10-20 07:38:47.522 22854-22854/org.sufficientlysecure.viewer E/Document Viewer.LibraryLoader: Native library cannot be loaded: 
                                                                                              java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.sufficientlysecure.viewer-364bcQin_DGkEPJTBg3tNQ==/base.apk", zip file "/data/app/org.sufficientlysecure.viewer-364bcQin_DGkEPJTBg3tNQ==/split_lib_dependencies_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-364bcQin_DGkEPJTBg3tNQ==/split_lib_slice_0_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-364bcQin_DGkEPJTBg3tNQ==/split_lib_slice_1_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-364bcQin_DGkEPJTBg3tNQ==/split_lib_slice_2_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-364bcQin_DGkEPJTBg3tNQ==/split_lib_slice_3_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-364bcQin_DGkEPJTBg3tNQ==/split_lib_slice_4_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-364bcQin_DGkEPJTBg3tNQ==/split_lib_slice_5_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-364bcQin_DGkEPJTBg3tNQ==/split_lib_slice_6_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-364bcQin_DGkEPJTBg3tNQ==/split_lib_slice_7_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-364bcQin_DGkEPJTBg3tNQ==/split_lib_slice_8_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-364bcQin_DGkEPJTBg3tNQ==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/org.sufficientlysecure.viewer-364bcQin_DGkEPJTBg3tNQ==/lib/x86, /system/lib, /system/vendor/lib]]] couldn't find "libebookdroid.so"
                                                                                                  at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
                                                                                                  at java.lang.System.loadLibrary(System.java:1657)
                                                                                                  at org.ebookdroid.EBookDroidLibraryLoader.load(EBookDroidLibraryLoader.java:17)
                                                                                                  at org.ebookdroid.droids.mupdf.codec.MuPdfContext.<clinit>(MuPdfContext.java:24)
                                                                                                  at java.lang.Class.newInstance(Native Method)
                                                                                                  at org.ebookdroid.core.models.DocumentModel.<init>(DocumentModel.java:71)
                                                                                                  at org.ebookdroid.ui.viewer.ViewerActivityController.afterCreate(ViewerActivityController.java:242)
                                                                                                  at org.ebookdroid.ui.viewer.ViewerActivityController.afterCreate(ViewerActivityController.java:98)
                                                                                                  at org.emdev.ui.AbstractActionActivity.onCreate(AbstractActionActivity.java:108)
                                                                                                  at android.app.Activity.performCreate(Activity.java:6975)
                                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
                                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
                                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                                                                                                  at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                                                                  at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                                  at android.os.Looper.loop(Looper.java:164)
                                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                                  at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
10-20 07:38:47.522 22854-22854/org.sufficientlysecure.viewer D/AndroidRuntime: Shutting down VM
10-20 07:38:47.524 22854-22854/org.sufficientlysecure.viewer E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: org.sufficientlysecure.viewer, PID: 22854
                                                                               java.lang.RuntimeException: Unable to start activity ComponentInfo{org.sufficientlysecure.viewer/org.ebookdroid.ui.viewer.ViewerActivity}: java.lang.RuntimeException: java.lang.ExceptionInInitializerError
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                                                                                   at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                   at android.os.Looper.loop(Looper.java:164)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                                Caused by: java.lang.RuntimeException: java.lang.ExceptionInInitializerError
                                                                                   at org.ebookdroid.core.models.DocumentModel.<init>(DocumentModel.java:74)
                                                                                   at org.ebookdroid.ui.viewer.ViewerActivityController.afterCreate(ViewerActivityController.java:242)
                                                                                   at org.ebookdroid.ui.viewer.ViewerActivityController.afterCreate(ViewerActivityController.java:98)
                                                                                   at org.emdev.ui.AbstractActionActivity.onCreate(AbstractActionActivity.java:108)
                                                                                   at android.app.Activity.performCreate(Activity.java:6975)
                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
                                                                                   at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                                   at android.os.Looper.loop(Looper.java:164) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6541) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
                                                                                Caused by: java.lang.ExceptionInInitializerError
                                                                                   at java.lang.Class.newInstance(Native Method)
                                                                                   at org.ebookdroid.core.models.DocumentModel.<init>(DocumentModel.java:71)
                                                                                   at org.ebookdroid.ui.viewer.ViewerActivityController.afterCreate(ViewerActivityController.java:242) 
                                                                                   at org.ebookdroid.ui.viewer.ViewerActivityController.afterCreate(ViewerActivityController.java:98) 
                                                                                   at org.emdev.ui.AbstractActionActivity.onCreate(AbstractActionActivity.java:108) 
                                                                                   at android.app.Activity.performCreate(Activity.java:6975) 
                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213) 
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770) 
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
                                                                                   at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                                   at android.os.Looper.loop(Looper.java:164) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6541) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
                                                                                Caused by: java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.sufficientlysecure.viewer-364bcQin_DGkEPJTBg3tNQ==/base.apk", zip file "/data/app/org.sufficientlysecure.viewer-364bcQin_DGkEPJTBg3tNQ==/split_lib_dependencies_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-364bcQin_DGkEPJTBg3tNQ==/split_lib_slice_0_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-364bcQin_DGkEPJTBg3tNQ==/split_lib_slice_1_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-364bcQin_DGkEPJTBg3tNQ==/split_lib_slice_2_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-364bcQin_DGkEPJTBg3tNQ==/split_lib_slice_3_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-364bcQin_DGkEPJTBg3tNQ==/split_lib_slice_4_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-364bcQin_DGkEPJTBg3tNQ==/split_lib_slice_5_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-364bcQin_DGkEPJTBg3tNQ==/split_lib_slice_6_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-364bcQin_DGkEPJTBg3tNQ==/split_lib_slice_7_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-364bcQin_DGkEPJTBg3tNQ==/split_lib_slice_8_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-364bcQin_DGkEPJTBg3tNQ==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/org.sufficientlysecure.viewer-364bcQin_DGkEPJTBg3tNQ==/lib/x86, /system/lib, /system/vendor/lib]]] couldn't find "libebookdroid.so"
                                                                                   at org.ebookdroid.EBookDroidLibraryLoader.load(EBookDroidLibraryLoader.java:21)
                                                                                   at org.ebookdroid.droids.mupdf.codec.MuPdfContext.<clinit>(MuPdfContext.java:24)
                                                                                   at java.lang.Class.newInstance(Native Method) 
                                                                                   at org.ebookdroid.core.models.DocumentModel.<init>(DocumentModel.java:71) 
                                                                                   at org.ebookdroid.ui.viewer.ViewerActivityController.afterCreate(ViewerActivityController.java:242) 
                                                                                   at org.ebookdroid.ui.viewer.ViewerActivityController.afterCreate(ViewerActivityController.java:98) 
                                                                                   at org.emdev.ui.AbstractActionActivity.onCreate(AbstractActionActivity.java:108) 
                                                                                   at android.app.Activity.performCreate(Activity.java:6975) 
                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213) 
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770) 
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
                                                                                   at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                                   at android.os.Looper.loop(Looper.java:164) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6541) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
10-20 07:38:47.524 22854-22854/org.sufficientlysecure.viewer E/AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.sufficientlysecure.viewer-364bcQin_DGkEPJTBg3tNQ==/base.apk", zip file "/data/app/org.sufficientlysecure.viewer-364bcQin_DGkEPJTBg3tNQ==/split_lib_dependencies_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-364bcQin_DGkEPJTBg3tNQ==/split_lib_slice_0_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-364bcQin_DGkEPJTBg3tNQ==/split_lib_slice_1_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-364bcQin_DGkEPJTBg3tNQ==/split_lib_slice_2_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-364bcQin_DGkEPJTBg3tNQ==/split_lib_slice_3_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-364bcQin_DGkEPJTBg3tNQ==/split_lib_slice_4_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-364bcQin_DGkEPJTBg3tNQ==/split_lib_slice_5_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-364bcQin_DGkEPJTBg3tNQ==/split_lib_slice_6_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-364bcQin_DGkEPJTBg3tNQ==/split_lib_slice_7_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-364bcQin_DGkEPJTBg3tNQ==/split_lib_slice_8_apk.apk", zip file "/data/app/org.sufficientlysecure.viewer-364bcQin_DGkEPJTBg3tNQ==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/org.sufficientlysecure.viewer-364bcQin_DGkEPJTBg3tNQ==/lib/x86, /system/lib, /system/vendor/lib]]] couldn't find "libebookdroid.so"
                                                                                   at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
                                                                                   at java.lang.System.loadLibrary(System.java:1657)
                                                                                   at org.ebookdroid.EBookDroidLibraryLoader.load(EBookDroidLibraryLoader.java:17)
                                                                                   	... 18 more
```

Crash on Emulator Nexus 5X API 26

Thank you so much.

**Comment by ericwa** [comment]
I am assuming you are compiling document-viewer yourself?

Did you run `init.sh` and `ndk-build` successfully? see: https://github.com/PrivacyApps/document-viewer/blob/master/README.md#build-with-gradle

**Comment by chihung93** [comment]
I run
1. init.sh  => successfully
2. ./gradlew ndk-build --stacktrace --info => BUILD FAILED

Android studio 2.3.3

```
* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':document-viewer'.
        at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:94)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:89)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:76)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.access$000(LifecycleProjectEvaluator.java:33)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:53)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:50)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:50)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:628)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:129)
        at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:62)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:38)
        at org.gradle.initialization.DefaultGradleLauncher$1.execute(DefaultGradleLauncher.java:161)
        at org.gradle.initialization.DefaultGradleLauncher$1.execute(DefaultGradleLauncher.java:158)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:158)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
        at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:44)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:29)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.gradle.internal.event.ListenerNotificationException: Failed to notify project evaluation listener.
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:55)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy16.afterEvaluate(Unknown Source)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:82)
        ... 56 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.android.sdklib.repository.AndroidSdkHandler
        at com.android.builder.sdk.DefaultSdkLoader.init(DefaultSdkLoader.java:377)
        at com.android.builder.sdk.DefaultSdkLoader.getSdkInfo(DefaultSdkLoader.java:360)
        at com.android.build.gradle.internal.SdkHandler.initTarget(SdkHandler.java:133)
        at com.android.build.gradle.BasePlugin.ensureTargetSetup(BasePlugin.java:671)
        at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:570)
        at com.android.build.gradle.BasePlugin.lambda$null$4(BasePlugin.java:526)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:81)
        at com.android.build.gradle.BasePlugin.lambda$createTasks$5(BasePlugin.java:522)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:93)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:82)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
        ... 61 more

```

**Comment by ericwa** [comment]
I haven't seen `./gradlew ndk-build` before, currently I don't think we can build the native code through gradle, you need to run the `ndk-build` command directly from the `document-viewer` subdirectory.

**Comment by chihung93** [comment]
@ericwa : 
Currently, I have run the latest ndk-build and have been successful.
Thanks for the support.

**Comment by chihung93** [comment]
One more question ^^.
Why don't you package the .so file in the libs directory?
I must build from ndk-build for generating file .so.
